### ISSUE TITLE
is it any different between btn.backgroundImageView.contentMode and UIButton-BackgroundContentMode?

### ISSUE THREAD

**Issue by litt1e-p** [devxoul/UIButton-BackgroundContentMode#1]
UIButton.backgroundImageView.contentMode can also set contentMode for UIButton's backgroundImage, so is it any different between btn.backgroundImageView.contentMode and UIButton-BackgroundContentMode? or something feature ?

**Comment by devxoul** [comment]
Hi @litt1e-p, UIButton doesn't have `backgroundImageView` property.

**Comment by litt1e-p** [comment]
ah, sorry My mistake. you did a great job

2015年12月31日星期四，Suyeol Jeon notifications@github.com 写道：

**Comment by devxoul** [comment]
Thanks :smile:
