### ISSUE TITLE
Picture becomes distorted in collectionView 

### ISSUE THREAD

**Issue by mding5692** [devxoul/UIButton-BackgroundContentMode#3]
I have buttons in a collectionView that are also images and enlarge to fill screen when pressed, originally I used imageViews with tap gesture recognizes but it was too hard to maintain and when I just used buttons and used imageViews, they would mess up the sizing.

So I used backgroundImageView because sizing is more automatic. However, often after scrolling around, the backgroundImages become distorted like this:

![screen shot 2017-08-29 at 5 11 37 pm](https://user-images.githubusercontent.com/9067177/29844504-8470ba16-8cdd-11e7-9fe5-29e270e02125.png)

This is the code for it, I'm using IOS Swift and imported the project using Cocoapods:

![screen shot 2017-08-29 at 5 14 42 pm](https://user-images.githubusercontent.com/9067177/29844525-98c506fc-8cdd-11e7-824c-ab979af13193.png)

**Comment by mding5692** [comment]
Stopped using this and just put an imageview underneath the button

**Comment by devxoul** [comment]
@mding5692 could you reproduce this bug on a new project?
